CREATE TABLE cleaned_data (
   primary_key INT NOT NULL,
   points FLOAT,
   price FLOAT,
   country INT,
   designation INT,
   province INT,
   region_1 INT,
   variety INT,
   winery INT,
   "1" FLOAT,
   "2" FLOAT,
   "3" FLOAT,
   "4" FLOAT,
   "5" FLOAT,
   "6" FLOAT,
   "7" FLOAT,
   "8" FLOAT,
   "9" FLOAT,
   "10" FLOAT,
   PRIMARY KEY (primary_key)
);